### ISSUE TITLE
Could you please convert this in a fork?

### ISSUE THREAD

**Issue by AmazingMech2418** [amazinigmech2418/Learning-C-#1]
@masterofthetiger

**Comment by MasterOfTheTiger** [comment]
You want me to compile it so it can be run? Is that what you mean?

**Comment by MasterOfTheTiger** [comment]
Okay, I need to know what operating system you are using?

**Comment by MasterOfTheTiger** [comment]
After I know your OS I can compile it. Okay @amazinigmech2418 ?

**Comment by AmazingMech2418** [comment]
Windows. Convert to exe please. @MasterOfTheTiger
